apiVersion: apps/v1
kind: Deployment

metadata:
  name: companyportal

spec:
  replicas: 1

  selector:
    matchLabels:
      app: companyportal

  template:
    metadata:
      labels:
        app: companyportal

    spec:
      containers:
      - name: companyportal
        image: jkarthi/companyportal:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 9090